messages:
  tpa-requester:
    text: " Вы отправили запрос к игроку %requested%!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1
  tpa-requested:
    text: " Вам отправил запрос на телепортацию игрок %requester%!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1

  tpa-requester-deny:
    text: " Игрок %requested% отменил ваш запрос!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1
  tpa-requested-deny:
    text: " Вы отменили телепортацию!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1

  tpa-requester-accept:
    text: " Игрок %requested% принял ваш запрос! Телепорт через %time% секунд!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1
  tpa-requested-accept:
    text: " Вы приняли телепортацию! Телепорт через %time% секунд!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1

  tpa-requester-timeout:
    text: " Игрок %requested% не принял ваш запрос!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1
  tpa-requested-timeout:
    text: " Вы не приняли запрос от игрока %requester%!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1

  tpa-cooldown:
    text: " Вы не приняли запрос от игрока %requester%!"
    sound: "BLOCK_NOTE_BLOCK_BIT"
    pitch: 1
    volume: 1
