name: Teleports
version: '1'
main: dev.thew.teleports.Teleports
api-version: '1.20'
author: Thew
commands:
  tpa:
    permission: teleports.tpa
  tpaccept:
    permission: teleports.tpaccept
  tpdeny:
    permission: teleports.tpdeny
  rtp:
    permission: teleports.rtp
    aliases:
      - randomtp
      - randtp
      - randomteleport
